version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:_{PORT_COMMAND}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      PORT_COMMAND: "docker ps | grep kafka_1 | cut -d: -f 2 | cut -d- -f 1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
