name: 3.0.x | Boot Smoke Tests | Boot Tcf
on:
  schedule:
    - cron : '10 0 * * *'
  workflow_dispatch:
jobs:
  boot_tcf_test:
    name: Boot Tcf Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.0.x
      project: boot:boot-tcf
      task: test
  boot_tcf_native_test:
    name: Boot Tcf Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.0.x
      project: boot:boot-tcf
      task: nativeTest
