name: 3.0.x | Data Smoke Tests | Data Mongodb Reactive
on:
  schedule:
    - cron : '10 0 * * *'
jobs:
  data_mongodb_reactive_app_test:
    name: Data Mongodb Reactive App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.0.x
      project: data:data-mongodb-reactive
      task: appTest
  data_mongodb_reactive_native_app_test:
    name: Data Mongodb Reactive Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.0.x
      project: data:data-mongodb-reactive
      task: nativeAppTest
