name: 3.1.x | Framework Smoke Tests | Hibernate Enhancer
on:
  workflow_dispatch:
jobs:
  hibernate_enhancer_app_test:
    name: Hibernate Enhancer App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.1.x
      project: framework:hibernate-enhancer
      task: appTest
  hibernate_enhancer_native_app_test:
    name: Hibernate Enhancer Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.1.x
      project: framework:hibernate-enhancer
      task: nativeAppTest
