name: 3.2.x | Framework Smoke Tests | Webmvc Jetty Tls
on:
  schedule:
    - cron : '30 0 * * *'
  workflow_dispatch:
jobs:
  webmvc_jetty_tls_app_test:
    name: Webmvc Jetty Tls App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.2.x
      project: framework:webmvc-jetty-tls
      task: appTest
      group_owners_secret_name: FRAMEWORK_OWNER_IDS
      test_owners_secret_name: WEBMVC_JETTY_TLS_OWNER_IDS
  webmvc_jetty_tls_native_app_test:
    name: Webmvc Jetty Tls Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.2.x
      project: framework:webmvc-jetty-tls
      task: nativeAppTest
      group_owners_secret_name: FRAMEWORK_OWNER_IDS
      test_owners_secret_name: WEBMVC_JETTY_TLS_OWNER_IDS
