name: 3.2.x | Integration Smoke Tests | Spring Pulsar
on:
  schedule:
    - cron : '30 0 * * *'
  workflow_dispatch:
jobs:
  spring_pulsar_app_test:
    name: Spring Pulsar App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.2.x
      project: integration:spring-pulsar
      task: appTest
      group_owners_secret_name: INTEGRATION_OWNER_IDS
      test_owners_secret_name: SPRING_PULSAR_OWNER_IDS
  spring_pulsar_native_app_test:
    name: Spring Pulsar Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.2.x
      project: integration:spring-pulsar
      task: nativeAppTest
      group_owners_secret_name: INTEGRATION_OWNER_IDS
      test_owners_secret_name: SPRING_PULSAR_OWNER_IDS
