name: 3.3.x | Framework Smoke Tests | Cache Redis
on:
  schedule:
    - cron : '40 0 * * *'
  workflow_dispatch:
jobs:
  cache_redis_app_test:
    name: Cache Redis App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.3.x
      project: framework:cache-redis
      task: appTest
  cache_redis_native_app_test:
    name: Cache Redis Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.3.x
      project: framework:cache-redis
      task: nativeAppTest
