name: 3.3.x | Framework Smoke Tests | Jdbc Postgresql
on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  jdbc_postgresql_app_test:
    name: Jdbc Postgresql App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.3.x
      project: framework:jdbc-postgresql
      task: appTest
  jdbc_postgresql_native_app_test:
    name: Jdbc Postgresql Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.3.x
      project: framework:jdbc-postgresql
      task: nativeAppTest
