name: 3.4.x | Framework Smoke Tests | Webflux Undertow
on:
  schedule:
    - cron : '30 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  webflux_undertow_app_test:
    name: Webflux Undertow App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webflux-undertow
      task: appTest
  webflux_undertow_native_app_test:
    name: Webflux Undertow Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webflux-undertow
      task: nativeAppTest
  webflux_undertow_test:
    name: Webflux Undertow Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webflux-undertow
      task: test
  webflux_undertow_native_test:
    name: Webflux Undertow Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webflux-undertow
      task: nativeTest
