name: 4.0.x | Integration Smoke Tests | Spring Pulsar
on:
  schedule:
    - cron : '50 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  spring_pulsar_app_test:
    name: Spring Pulsar App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: integration:spring-pulsar
      task: appTest
  spring_pulsar_native_app_test:
    name: Spring Pulsar Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: integration:spring-pulsar
      task: nativeAppTest
      graal_version: 25
