name: 4.0.x | Security Smoke Tests | Security Oauth2 Resource Server
on:
  schedule:
    - cron: '40 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  security_oauth2_resource_server_app_test:
    name: Security Oauth2 Resource Server App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-oauth2-resource-server
      task: appTest
  security_oauth2_resource_server_native_app_test:
    name: Security Oauth2 Resource Server Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-oauth2-resource-server
      task: nativeAppTest
      graal_version: 25
