name: 4.0.x | Security Smoke Tests | Security Ldap
on:
  schedule:
    - cron : '50 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  security_ldap_app_test:
    name: Security Ldap App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-ldap
      task: appTest
  security_ldap_native_app_test:
    name: Security Ldap Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-ldap
      task: nativeAppTest
      graal_version: 25
  security_ldap_test:
    name: Security Ldap Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-ldap
      task: test
  security_ldap_native_test:
    name: Security Ldap Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-ldap
      task: nativeTest
      graal_version: 25
