name: 4.0.x | Framework Smoke Tests | Aspect
on:
  schedule:
    - cron : '50 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  aspect_app_test:
    name: Aspect App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: main
      project: framework:aspect
      task: appTest
  aspect_native_app_test:
    name: Aspect Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: main
      project: framework:aspect
      task: nativeAppTest
