name: Boot Smoke Tests | Servlet Tomcat
on:
  push:
    branches:
      - '3.0.x'
jobs:
  servlet_tomcat_app_test:
    name: Servlet Tomcat App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:servlet-tomcat
      task: appTest
  servlet_tomcat_native_app_test:
    name: Servlet Tomcat Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:servlet-tomcat
      task: nativeAppTest
