name: Boot Smoke Tests | Actuator Webflux Mgmt Port
on:
  push:
    branches:
      - '3.0.x'
jobs:
  actuator_webflux_mgmt_port_app_test:
    name: Actuator Webflux Mgmt Port App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:actuator-webflux-mgmt-port
      task: appTest
  actuator_webflux_mgmt_port_native_app_test:
    name: Actuator Webflux Mgmt Port Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:actuator-webflux-mgmt-port
      task: nativeAppTest
