name: Boot Smoke Tests | Servlet Component Scan
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  servlet_component_scan_app_test:
    name: Servlet Component Scan App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:servlet-component-scan
      task: appTest
  servlet_component_scan_native_app_test:
    name: Servlet Component Scan Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:servlet-component-scan
      task: nativeAppTest
