name: Boot Smoke Tests | Servlet Undertow
on:
  push:
    branches:
      - '3.1.x'
jobs:
  servlet_undertow_app_test:
    name: Servlet Undertow App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:servlet-undertow
      task: appTest
  servlet_undertow_native_app_test:
    name: Servlet Undertow Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:servlet-undertow
      task: nativeAppTest
