name: Boot Smoke Tests | Logging Logback Spring Xml
on:
  push:
    branches:
      - 'main'
jobs:
  logging_logback_spring_xml_app_test:
    name: Logging Logback Spring Xml App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:logging-logback-spring-xml
      task: appTest
  logging_logback_spring_xml_native_app_test:
    name: Logging Logback Spring Xml Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:logging-logback-spring-xml
      task: nativeAppTest
