name: Boot Smoke Tests | Xml Config
on:
  push:
    branches:
      - 'main'
jobs:
  xml_config_app_test:
    name: Xml Config App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:xml-config
      task: appTest
  xml_config_native_app_test:
    name: Xml Config Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:xml-config
      task: nativeAppTest
