name: Boot Smoke Tests | Logging Logback
on:
  push:
    branches:
      - '3.1.x'
jobs:
  logging_logback_app_test:
    name: Logging Logback App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:logging-logback
      task: appTest
  logging_logback_native_app_test:
    name: Logging Logback Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:logging-logback
      task: nativeAppTest
