name: Boot Smoke Tests | Thymeleaf Webflux
on:
  push:
    branches:
      - 'main'
jobs:
  thymeleaf_webflux_app_test:
    name: Thymeleaf Webflux App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:thymeleaf-webflux
      task: appTest
  thymeleaf_webflux_native_app_test:
    name: Thymeleaf Webflux Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:thymeleaf-webflux
      task: nativeAppTest
