name: Cloud Smoke Tests | Cloud Stream Kafka
on:
  push:
    branches:
      - '3.1.x'
jobs:
  cloud_stream_kafka_app_test:
    name: Cloud Stream Kafka App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-kafka
      task: appTest
  cloud_stream_kafka_native_app_test:
    name: Cloud Stream Kafka Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-kafka
      task: nativeAppTest
