name: Cloud Smoke Tests | Cloud Function Webflux
on:
  push:
    branches:
      - '3.1.x'
jobs:
  cloud_function_webflux_app_test:
    name: Cloud Function Webflux App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-function-webflux
      task: appTest
  cloud_function_webflux_native_app_test:
    name: Cloud Function Webflux Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-function-webflux
      task: nativeAppTest
