name: Cloud Smoke Tests | Cloud Discovery Consul
on:
  push:
    branches:
      - 'main'
jobs:
  cloud_discovery_consul_app_test:
    name: Cloud Discovery Consul App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-discovery-consul
      task: appTest
  cloud_discovery_consul_native_app_test:
    name: Cloud Discovery Consul Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-discovery-consul
      task: nativeAppTest
