name: Cloud Smoke Tests | Cloud Function Web
on:
  push:
    branches:
      - '3.0.x'
jobs:
  cloud_function_web_app_test:
    name: Cloud Function Web App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-function-web
      task: appTest
  cloud_function_web_native_app_test:
    name: Cloud Function Web Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-function-web
      task: nativeAppTest
