name: Data Smoke Tests | Data Cassandra
on:
  push:
    branches:
      - 'main'
jobs:
  data_cassandra_app_test:
    name: Data Cassandra App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-cassandra
      task: appTest
  data_cassandra_native_app_test:
    name: Data Cassandra Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-cassandra
      task: nativeAppTest
