name: Data Smoke Tests | Data Jdbc Postgresql
on:
  push:
    branches:
      - 'main'
jobs:
  data_jdbc_postgresql_app_test:
    name: Data Jdbc Postgresql App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-jdbc-postgresql
      task: appTest
  data_jdbc_postgresql_native_app_test:
    name: Data Jdbc Postgresql Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-jdbc-postgresql
      task: nativeAppTest
