name: Data Smoke Tests | Data Jpa
on:
  push:
    branches:
      - '3.1.x'
jobs:
  data_jpa_app_test:
    name: Data Jpa App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-jpa
      task: appTest
  data_jpa_native_app_test:
    name: Data Jpa Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-jpa
      task: nativeAppTest
  data_jpa_test:
    name: Data Jpa Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-jpa
      task: test
  data_jpa_native_test:
    name: Data Jpa Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-jpa
      task: nativeTest
