name: Data Smoke Tests | Data Neo4j
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  data_neo4j_app_test:
    name: Data Neo4j App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-neo4j
      task: appTest
  data_neo4j_native_app_test:
    name: Data Neo4j Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-neo4j
      task: nativeAppTest
