name: Framework Smoke Tests | Cache Hazelcast
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  cache_hazelcast_app_test:
    name: Cache Hazelcast App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:cache-hazelcast
      task: appTest
  cache_hazelcast_native_app_test:
    name: Cache Hazelcast Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:cache-hazelcast
      task: nativeAppTest
