name: Framework Smoke Tests | Hibernate
on:
  push:
    branches:
      - 'main'
jobs:
  hibernate_app_test:
    name: Hibernate App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:hibernate
      task: appTest
  hibernate_native_app_test:
    name: Hibernate Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:hibernate
      task: nativeAppTest
