name: Framework Smoke Tests | Webmvc Tomcat Tls
on:
  push:
    branches:
      - '3.0.x'
jobs:
  webmvc_tomcat_tls_app_test:
    name: Webmvc Tomcat Tls App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webmvc-tomcat-tls
      task: appTest
  webmvc_tomcat_tls_native_app_test:
    name: Webmvc Tomcat Tls Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webmvc-tomcat-tls
      task: nativeAppTest
