name: Framework Smoke Tests | Webmvc Jetty
on:
  push:
    branches:
      - '3.1.x'
jobs:
  webmvc_jetty_app_test:
    name: Webmvc Jetty App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty
      task: appTest
  webmvc_jetty_native_app_test:
    name: Webmvc Jetty Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty
      task: nativeAppTest
  webmvc_jetty_test:
    name: Webmvc Jetty Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty
      task: test
  webmvc_jetty_native_test:
    name: Webmvc Jetty Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty
      task: nativeTest
