name: Framework Smoke Tests | Hibernate Enhancer
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  hibernate_enhancer_app_test:
    name: Hibernate Enhancer App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:hibernate-enhancer
      task: appTest
  hibernate_enhancer_native_app_test:
    name: Hibernate Enhancer Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:hibernate-enhancer
      task: nativeAppTest
