name: Framework Smoke Tests | Websocket Tomcat
on:
  push:
    branches:
      - 'main'
jobs:
  websocket_tomcat_app_test:
    name: Websocket Tomcat App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:websocket-tomcat
      task: appTest
  websocket_tomcat_native_app_test:
    name: Websocket Tomcat Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:websocket-tomcat
      task: nativeAppTest
