name: Framework Smoke Tests | Quartz
on:
  push:
    branches:
      - '3.0.x'
jobs:
  quartz_app_test:
    name: Quartz App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:quartz
      task: appTest
  quartz_native_app_test:
    name: Quartz Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:quartz
      task: nativeAppTest
