name: Framework Smoke Tests | Transactional Event Listener
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  transactional_event_listener_app_test:
    name: Transactional Event Listener App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:transactional-event-listener
      task: appTest
  transactional_event_listener_native_app_test:
    name: Transactional Event Listener Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:transactional-event-listener
      task: nativeAppTest
