name: Framework Smoke Tests | Websocket Undertow
on:
  push:
    branches:
      - '3.1.x'
jobs:
  websocket_undertow_app_test:
    name: Websocket Undertow App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:websocket-undertow
      task: appTest
  websocket_undertow_native_app_test:
    name: Websocket Undertow Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:websocket-undertow
      task: nativeAppTest
