name: Framework Smoke Tests | Webclient
on:
  push:
    branches:
      - 'main'
jobs:
  webclient_app_test:
    name: Webclient App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webclient
      task: appTest
  webclient_native_app_test:
    name: Webclient Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webclient
      task: nativeAppTest
