name: Framework Smoke Tests | Webmvc Jetty Tls
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  webmvc_jetty_tls_app_test:
    name: Webmvc Jetty Tls App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty-tls
      task: appTest
  webmvc_jetty_tls_native_app_test:
    name: Webmvc Jetty Tls Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webmvc-jetty-tls
      task: nativeAppTest
