name: Graphql Smoke Tests | Graphql Webmvc
on:
  push:
    branches:
      - 'main'
jobs:
  graphql_webmvc_app_test:
    name: Graphql Webmvc App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: graphql:graphql-webmvc
      task: appTest
  graphql_webmvc_native_app_test:
    name: Graphql Webmvc Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: graphql:graphql-webmvc
      task: nativeAppTest
  graphql_webmvc_test:
    name: Graphql Webmvc Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: graphql:graphql-webmvc
      task: test
  graphql_webmvc_native_test:
    name: Graphql Webmvc Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: graphql:graphql-webmvc
      task: nativeTest
