name: Integration Smoke Tests | Spring Kafka
on:
  push:
    branches:
      - 'main'
jobs:
  spring_kafka_app_test:
    name: Spring Kafka App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: integration:spring-kafka
      task: appTest
  spring_kafka_native_app_test:
    name: Spring Kafka Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: integration:spring-kafka
      task: nativeAppTest
