name: Integration Smoke Tests | Spring Pulsar
on:
  push:
    branches:
      - '3.0.x'
jobs:
  spring_pulsar_app_test:
    name: Spring Pulsar App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: integration:spring-pulsar
      task: appTest
  spring_pulsar_native_app_test:
    name: Spring Pulsar Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: integration:spring-pulsar
      task: nativeAppTest
