name: Security Smoke Tests | Ldap Odm
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  ldap_odm_app_test:
    name: Ldap Odm App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: security:ldap-odm
      task: appTest
  ldap_odm_native_app_test:
    name: Ldap Odm Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: security:ldap-odm
      task: nativeAppTest
  ldap_odm_test:
    name: Ldap Odm Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: security:ldap-odm
      task: test
  ldap_odm_native_test:
    name: Ldap Odm Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: security:ldap-odm
      task: nativeTest
